name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        uses: cypress-io/github-action@v4
        with:
          build: npm run build # if you have a build step
          start: npm start # if you need to start a server
          wait-on: "http://localhost:3000" # if your app runs on a specific port
          wait-on-timeout: 60 # wait for 60 seconds for the server to start
